author: Gravel # 作者
description: Gravel's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan

comment: gitment

# Gitment
gitment_owner: LeonGravel
gitment_repo: Gitment-Issue-Page
gitment_oauth_id: 68512493679a784821d2
gitment_oauth_secret: 8ca49523a6640b73cfdfc5148c1a2910f6246964

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  #banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/13548712?s=460&v=4
  description: "一个脱离了低级趣味的空栈工程师"
 # weibo_username: gravel
  twitter_username: leebroncc
  github_username: leongravel
  zhihu_username: gravel-20
  #douban_username: gravel

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
